name: task_tech
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  custom_navigation_bar: ^0.8.2
  flutter_rounded_progress_bar: ^0.2.0
  intl: ^0.17.0
  dotted_border: ^2.0.0+3
  file_picker: ^5.2.4
  simple_gradient_text: ^1.2.4
  smooth_star_rating_null_safety: ^1.0.4+2
  syncfusion_flutter_sliders: ^20.4.49
  another_xlider: ^1.1.2
  syncfusion_flutter_core:
  google_maps_flutter: ^2.2.4
  flutter_switch: ^0.3.2
  http: ^0.13.5
  path: ^1.8.2
  image_picker: ^0.8.7+4
  image_cropper: ^3.0.3
  google_maps_flutter_web: ^0.5.0+1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - icons/
    - icons/
