const List<String> educationList = [
  'Ain Shams University',
  'Al Alamein International University',
  'Al-Azhar University',
  'Alexandria University',
  'Arish University',
  'Assiut University',
  'Aswan University',
  'Badr University in Cairo',
  'Benha University',
  'Beni-Suef University',
  'Cairo University',
  'Damanhour University',
  'Damietta University',
  'Delta University for Science and Technology',
  'Egyptian Chinese University',
  'Egypt-Japan University of Science and Technology',
  'Fayoum University',
  'Future University in Egypt',
  'Galala University',
  'Helwan University',
  'Kafrelsheikh University',
  'Luxor University',
  'Mansoura University',
  'Matrouh University',
  'Menoufia University',
  'Minia University',
  'Misr International University',
  'New Valley University',
  'Pharos University in Alexandria',
  'Port Said University',
  'Sinai University',
  'Sohag university',
  'South Valley University',
  'Suez Canal University',
  'Suez University',
  'Tanta University',
  'The American University in Cairo',
  'The Arab Academy for Management',
  'Banking and Financial Sciences',
  'The British University in Egypt',
  'The German University in Cairo',
  "Université Française d'Égypte",
  'University of Sadat City',
  'University of Science and Technology at Zewail City',
  'Zagazig University',
  'Massachusetts Institute of Technology (MIT)',
  'Harvard University',
  'University of Oxford',
  'University of Cambridge',
  'ETH Zurich (Swiss Federal Institute of Technology)',
  'University of Tokyo',
  'Universite PSL',
];

const List<String> categories = [
  'Web Design',
  'Marketing',
  'Business',
  'Software Engineering',
  'Web Developer',
  'App Developer',
  'Product Manager',
  'Accountant',
  'Ui/Ux Design',
  'Graphics Designer'
];

const List<String> currencyList = <String>[
  'EUR',
  'USD',
  'SAR',
  'CHF',
  'EGP',
  'GBP',
];

const List<String> frequencyList = <String>[
  'per hour',
  'per day',
  'per week',
  'per month'
];
